server:
  port: 8080

spring:
  application:
    name: websocket-zhangwei
microservice:
  websocket:
    enabled: true
    async-send-timeout: 0
    max-session-idle-timeout: 1800000
    max-binary-message-buffer-size: 16777216
