spring:
  application:
    name: authorization-server
  datasource:
    schema: classpath:schema/oauth2_postgres_schema.sql
    initialization-mode: embedded
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/oauth2
          druid: #以下均为默认值
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall
            share-prepared-statements: true
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    password:
    database: 0
    jedis:
      pool:
        max-active: 8 #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8  #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0 #最小等待连接中的数量,设 0 为没有限制
  security:
    strategy: MODE_INHERITABLETHREADLOCAL
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  jackson:
    generator:
      write_numbers_as_strings: true
  messages:
    basename: i18n/messages
  freemarker:
    cache: false
    suffix: .html
    charset: UTF-8
    enabled: true
    settings:
      number_format: '0.##'
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1800000
  shareSecurityContext: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.microservice.beans
  check-config-location: true

xxl:
  job:
    admin:
      addresses: http://localhost:9000/xxl-job-admin # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    accessToken: '' # 执行器通讯TOKEN [选填]：非空时启用；
    executor:
      appname: ${spring.application.name}  # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      address: '' # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      ip: '' # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 9001 # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath: /home/centos/tmp/xxl # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；

management:
  endpoints:
    web:
      exposure:
        include: "*"
