spring:
  application:
    name: authorization-server
  redis:
    host: localhost
    port: 6379
  datasource:
    schema: classpath:schema/oauth2_mysql_schema.sql
    initialization-mode: embedded
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          username: root
          password: jzbr
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          druid: #以下均为默认值
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall
            share-prepared-statements: true
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driverClassName: com.mysql.jdbc.Driver
  #    filters: stat,wall
  #    druid:
  #      url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  #      username: root
  #      password: jzbr
  #      initialSize: 5
  #      minIdle: 5
  #      maxActive: 20
  #      maxWait: 60000
  #      timeBetweenEvictionRunsMillis: 60000
  #      minEvictableIdleTimeMillis: 300000
  #      validationQuery: SELECT 1 FROM DUAL
  #      testWhileIdle: true
  #      testOnBorrow: false
  #      testOnReturn: false
  #      poolPreparedStatements: false
  #      maxPoolPreparedStatementPerConnectionSize: 20
  #      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.microservice.beans
  check-config-location: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
