spring:
  profiles:
    active: dev1

---
server:
  port: 8888
spring:
  profiles: dev1
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        #        hostname: 10.29.23.178
        #        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.hostname}:${server.port}
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        #        port: ${server.port} #${SERVER_PORT:${server.port}}
        healthCheckInterval: 15s
        health-check-critical-timeout: 60s
        tags: uat
        heartbeat:
          enabled: true
  application:
    name: scheduler-example-executor-dev1
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8 #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8  #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0 #最小等待连接中的数量,设 0 为没有限制
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 1000ms

microservice:
  scheduler:
#    cluster-address: 192.168.40.1:9991;192.168.40.1:9992
    cluster-address: 192.168.40.1:9992
    register-name: ${spring.application.name}
    swagger-enable: true

---
server:
  port: 8889
spring:
  profiles: dev2
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        #        hostname: 10.29.23.178
        #        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.hostname}:${server.port}
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        #        port: ${server.port} #${SERVER_PORT:${server.port}}
        healthCheckInterval: 15s
        health-check-critical-timeout: 60s
        tags: uat
        heartbeat:
          enabled: true
  application:
    name: scheduler-example-executor-dev2
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8 #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8  #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0 #最小等待连接中的数量,设 0 为没有限制
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 1000ms

microservice:
  scheduler:
    #    cluster-address: 192.168.40.1:9991;192.168.40.1:9992
    cluster-address: 192.168.40.1:9992
    register-name: ${spring.application.name}
    swagger-enable: true