server:
  port: 8001

spring:
  application:
    name: sentinel-zhangwei

project:
  name: ${spring.application.name}

csp:
  sentinel:
    dashboard:
      server: 192.168.40.1:8008
    api:
      port: 8719
    heartbeat:
      interval:
        ms: 5000
      client:
        ip: 192.168.40.1

#  csp.sentinel.dashboard.server	控制台的地址，指定控制台后客户端会自动向该地址发送心跳包。地址格式为：hostIp:port	String	null	是
#  csp.sentinel.heartbeat.interval.ms	心跳包发送周期，单位毫秒	long	null	非必需，若不进行配置，则会从相应的 HeartbeatSender 中提取默认值
#  csp.sentinel.api.port	本地启动 HTTP API Server 的端口号	int	8719	否
#  csp.sentinel.heartbeat.client.ip	指定心跳包中本机的 IP	String	-	若不指定则通过 HostNameUtil 解析；该配置项多用于多网卡环境

# 启动命令添加: -Dcsp.sentinel.dashboard.server=192.168.40.1:8008